### ISSUE TITLE
How is this different

### ISSUE THREAD

**Issue by Firesphere** [silverstripeltd/silverstripe-csp#9]
How is this different or any additional value to `firesphere/silverstripe-csp-headers`?

**Comment by sunnysideup** [comment]
@Firesphere @adrhumphreys  - is there any way the two modules can be merged on focus on different areas?

**Comment by Firesphere** [comment]
Aside from the Middleware, which is an open issue, there is barely any benefits, from what I can see.

Sub-micro-modules for implementing "quick" updates to known entities, e.g. YouTube, is easy enough to implement with some micro-modules and yaml either way... I had a look/thought about the whole concept of "Fragments", but it seems quite overkill and pointless. Since my module allows adding/removing domains via the CMS, the additional value of Fragments, requiring a whole deployment, compared to adding a domain in the CMS, seems quite limited, to be honest.

**Comment by satrun77** [comment]
Closing, is not an issue. Open Source is open for all ideas :)
